### PR TITLE
allow skipping of manifest build process

### PR DESCRIPTION
**Pull request by JamesClonk**
Signed-off by Fabio Berchtold <fabio.berchtold@swisscom.com>

### CODE REVIEW

**Comment by JamesClonk** [comment]
This deploy option will allow for skipping the manifest build process, in case the deployment manifest was already prepared manually or otherwise beforehand.
Otherwise bosh-workspace would interfere with the default bosh-cli `deploy` if it determines the deployment manifest to be a project deployment, for example if a `templates` property is found.

**Comment by allomov** [comment]
As I see there is no need in this option.

If you set your deployment to manifest without `templates` field, it will skip any template rendering and process request with default bosh cli. It is done automatically and I can't see an idea behind this option.

Could you check if `project_deployment?` method satisfies your case?

**Comment by rkoster** [comment]
I second what @allomov said. I don't really understand the use case.

**Comment by JamesClonk** [comment]
The problem is that I have a deployment manifest with a `templates` and therefore satisfies `project_deployment?`, but it's content is not meant for bosh-workspace and hence the deploy breaks because it tries to run a manifest merge/build with invalid data.
How can I skip bosh-workspace's additional handling and use only the vanilla `deploy` of the bosh-cli in this case?

**Comment by allomov** [comment]
The `template` section is not necessary for bosh manifest. Why do you need to have it?

**Comment by JamesClonk** [comment]
My deployment manifest contains a `templates` section because I have another script that does some more complicated spiff magic according to what's configured in there (I'm doing a multiple step manifest generation for Diego to be more specific).

I'd rather have a simple option to skip the bosh-workspace deploy/merge behavior than having to rename the `templates` into something else, as it wouldn't fit anymore with all our other deployment manifests.
Removing the bosh-workspace gem is also not an option as I'm also reliant on other features of it like for example the `deployments/file.yml` / `.deployments/file.yml` workflow.

This is actually the main reason behind the curtains why I need such an option in the first place, as even when I specifically target an already merged and complete deployment manifest in the `.deployments/` folder, bosh-workspace during deploy still goes to `deployments/` first and takes the manifest file from there and starts trying to do the merging/building and overwriting whats in `.deployments/`.
I'd actually be happy as another possibility to solve my problem if bosh-workspace could be told to not do that if I specifically targeted a file under `.deployments/` manually with ```bosh deployment .deployment/diego.yml``` before.
But this seemed to be the more complicated way to go about, so I decided on the simple option :smile:.

**Comment by JamesClonk** [comment]
closing this in favor of https://github.com/cloudfoundry-incubator/bosh-workspace/pull/88

**Pull request closed without merging**
