### PR TITLE
add 'build deployment' to allow building of deployment without triggering deploy

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by longnguyen11288** [comment]
:+1:

**Comment by rkoster** [comment]
@drnic could you add some tests for it?

**Comment by rkoster** [comment]
0.9.4 now comes with [shared rspec examples](rake release) which can be used to test your deployment manifest. Example usage can be found here: https://github.com/cloudfoundry-community/docker-services-boshworkspace/pull/36

**Comment by allomov** [comment]
Oh, I really wanted to see this functionality in upstream. This can be suitable for many reasons, not only testing. For instance you can work with bosh-init manifests with `bosh-workspace`.

**Comment by allomov** [comment]
I am going to create PR for this soon.

**Pull request closed without merging**
